
DIRDATA := data/
DIRSRC := src/

INTERP := python3

pack:
	$(INTERP) $(DIRSRC)ejercicioPropuestoPack.py

unpack:
	$(INTERP) $(DIRSRC)ejercicioPropuestoUnpack.py

clean:
	rm -rf *~ $(DIRSRC)*~ $(DIRDATA)*~

